@startuml GATOSQL
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Usuario", "El jugador")

package "Capa presentacion" as PRESENTACION {
  component UI as "Interface de usuario"
}

package "Capa de aplicacion" as APLICATION{

  component Juego as "JuegoGato"

}

package "ENTITY" as ENTITY{

  component tablero as "Tablero"
  note right : implementa un observer

  component Jugador as "Jugador"
  note right : usa observer
}

package "LOGDB" as LOGICA{

  component LOGTABLERO as "Tablero"
  note right : usa observer

}

package "DAO" as DAO{

  component DB as "DB"
  component DBFACTORY as "FACTORY"{
    note right : implementado como singlenton
  }

  component JMYSQL as "Base de datos MySQL"
  note right : implementacion MySQL

  component JSQLITE as "Base de datos SQLite"
  note right : implementacion SQLite

  component JFIREBASE as "Base de datos FireBase"
  note right : implementacion FireBase

}

Rel(UI, Juego, "Interactua con")
Rel(Juego, tablero, "Interactua con")
Rel(Juego, Jugador, "Usa")
Rel(tablero, DB, "Accede")

Rel(LOGTABLERO, tablero, "Avisa los cambios")
Rel(Jugador, tablero, "Avisa los cambios")

Rel(DB, DBFACTORY, "Crea")
Rel(DBFACTORY, JMYSQL, "Crea")
Rel(DBFACTORY, JSQLITE, "Crea por singlenton")
Rel(DBFACTORY, JFIREBASE, "Crea por singlenton")

Rel(personAlias, UI, "Play")

@enduml